name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
        persist-credentials: false
        fetch-depth: 0 

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Team-ANANA/docker-images
        persist-credentials: false
        fetch-depth: 0 

    - name: Build the Docker image
      run: |
        ls
        pwd
        docker build . --tag test-image
        docker images
        
    - name: Docker Login
      env:
          PWD: ${{ secrets.DOCKERHUB_PWD }}
      uses: docker/login-action@v2.0.0
      with:
        username: team0anana
        password: $PWD
     #   logout: false
    - name: Publishing to dockerhub
      run: |
        echo "Hey sisdfa"
        
             
    

 
      
          
