name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0 
        
    - name: Docker Login
      env:
          PWD: ${{ secrets.DOCKERHUB_PWD }}
      uses: docker/login-action@v2.0.0
      with:
        username: team0anana
        password: $PWD

    - name: Build the Docker image
      run: |
        docker build -t team0anana/csc302 .
        docker push team0anana/csc302
        

        
             
    

 
      
          
