name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Team-ANANA/docker-images
        path: my-tools

    - name: Build the Docker image
      run: |
        ls
        pwd
        docker build . --tag test-image
        docker save -o test-image.tar test-image 
        echo "Hey"
        pwd
        ls -l
        ls ..
        git remote -v
        cd .. && git remote -v
