name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]
    types: [closed]

jobs:

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0 
        
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: |
        docker build -t team0anana/csc302:frontend ./src/frontend
        docker build -t team0anana/csc302:backend ./src/api
        docker push team0anana/csc302:frontend
        docker push team0anana/csc302:backend
        
        

        
             
    

 
      
          
