name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Team-ANANA/docker-images
        path: my-tools

    - name: Build the Docker image
      run: |
        ls
        pwd
        docker build ./main --tag test-image
        docker save -o ./my-tools/test-image.tar test-image 
        cd ./my-tools && git add . && git commit -m "whatever commit" && git push origin main
