name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
        persist-credentials: false
        fetch-depth: 0 

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Team-ANANA/docker-images
        path: my-tools
        persist-credentials: false
        fetch-depth: 0 

    - name: Build the Docker image
      run: |
        ls
        pwd
        docker build ./main --tag test-image
        docker save -o ./my-tools/test-image.tar test-image 
        
    - name: Commit files
      run: |
        cd ./my-tools
        git config --local user.email "hao.xin.chao@mail.utoronto.ca"
        git config --local user.name "Jason-HaoXinChao"
        git add .
        git commit -m "Add changes" -a
        git push https://Jason-HaoXinChao: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@github.com/Team-ANANA/docker-images.git/ --all
                
#     - name: GitHub Push
#       # You may pin to the exact commit or the version.
#       # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
#       uses: ad-m/github-push-action@v0.6.0
#       with:
#         # github_token: $\{{ secrets.GH_TOKEN }}
#         github_token: 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
#         # Destination repisitory to push changes
#         repository: Team-ANANA/docker-images
#         branch: main
#         directory: ./my-tools
