# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Unit Test

on:
  pull_request:
    branches: [ "frontend" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/frontend/web
    - name: run npm ci
      working-directory: ./src/frontend/web
      run: npm ci
    - name: npm run build
      working-directory: ./src/frontend/web
      run: npm run build --if-present
    - name: run npm test
      working-directory: ./src/frontend/web
      run: npm test
